jobs:
  Build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-node@v2-beta
      with:
        cache: npm
        check-latest: true
        node-version: '16'
    - continue-on-error: true
      name: Install node modules
      run: npm ci
    - continue-on-error: true
      name: Do local build
      run: npm run-script build
    - continue-on-error: true
      name: Do production build
      run: npm run-script build-production
  Lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-node@v2-beta
      with:
        cache: npm
        check-latest: true
        node-version: '16'
    - continue-on-error: true
      name: Install node modules
      run: npm ci
    - continue-on-error: true
      name: Install node modules
      run: npm run-script lint
name: Verify Build Workflow
on:
  repository_dispatch:
    types: trigger-ga___portal-verify.yml
