jobs:
  sendRebuildDispatchEvent:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Send rebuild-apiman-antora-docs repository dispatch event to apiman/apiman-docs
        to trigger the Apiman Antora docs to be rebuilt and redeployed.
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
        event-type: rebuild-apiman-antora-docs
        repository: apiman/apiman-docs
        token: ${{ secrets.REPO_DISPATCH_ACCESS_TOKEN }}
name: Trigger rebuild and redeployment of Apiman docs website
on:
  repository_dispatch:
    types: trigger-ga___trigger-docs-rebuild-redeploy.yml
